django_blog/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.home, name='home'),
    path('posts/', views.PostListView.as_view(), name='post-list'),
    path('post/<int:pk>/', views.PostDetailView.as_view(), name='post-detail'),
    path('post/new/', views.PostCreateView.as_view(), name='post-create'),
    path('post/<int:pk>/update/', views.PostUpdateView.as_view(), name='post-update'),
    path('post/<int:pk>/delete/', views.PostDeleteView.as_view(), name='post-delete'),
    # Comment URLs
    path('post/<int:pk>/comments/new/', views.CommentCreateView.as_view(), name='add_comment'),
    path('comment/<int:pk>/update/', views.CommentUpdateView.as_view(), name='edit_comment'),
    path('comment/<int:pk>/delete/', views.CommentDeleteView.as_view(), name='delete_comment'),
    # Authentication URLs
    path('register/', views.RegisterView.as_view(), name='register'),
    path('login/', views.CustomLoginView.as_view(), name='login'),
    path('logout/', views.CustomLogoutView.as_view(), name='logout'),
    path('profile/', views.profile, name='profile'),
    # Tag and Search URLs
    path('tags/<slug:tag_slug>/', views.PostByTagListView.as_view(), name='tagged'),
    path('search/', views.search, name='search'),
]

django_blog/django_blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("blog.urls")),
]

django_blog/blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager

# Create your models here.

class Post(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField()
    published_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts')
    tags = TaggableManager()
    tags = TaggableManager()

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse('blog:post-detail', kwargs={'pk': self.pk})


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='comments')
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['created_at']

    def __str__(self):
        return f'Comment by {self.author.username} on {self.post.title}'

django_blog/blog/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Post, Comment
from taggit.forms import TagField, TagWidget


class CustomUserCreationForm(UserCreationForm):
    email = forms.EmailField(required=True)
    first_name = forms.CharField(max_length=30, required=False)
    last_name = forms.CharField(max_length=30, required=False)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2')

    def save(self, commit=True):
        user = super().save(commit=False)
        user.email = self.cleaned_data['email']
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        if commit:
            user.save()
        return user


class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField(required=True)
    
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Add Bootstrap classes to form fields
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


# Add Bootstrap classes to CustomUserCreationForm fields
for field_name, field in CustomUserCreationForm.base_fields.items():
    field.widget.attrs['class'] = 'form-control'


class PostForm(forms.ModelForm):
    tags = TagField(
        required=False,
        widget=TagWidget()
    )

    class Meta:
        model = Post
        fields = ['title', 'content', 'tags']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter post title'}),
            'content': forms.Textarea(attrs={'class': 'form-control', 'rows': 8, 'placeholder': 'Write your post content here...'}),
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']
        widgets = {
            'content': forms.Textarea(attrs={
                'class': 'form-control',
                'rows': 3,
                'placeholder': 'Write your comment here...',
                'required': True
            }),
        }

    def clean_content(self):
        content = self.cleaned_data.get('content')
        if not content or content.strip() == '':
            raise forms.ValidationError('Comment content cannot be empty.')
        if len(content) < 5:
            raise forms.ValidationError('Comment must be at least 5 characters long.')
        return content

django_blog/blog/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib import messages
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView
from django.urls import reverse_lazy
from .models import Post, Comment
from .forms import CustomUserCreationForm, UserUpdateForm, CommentForm, PostForm
from taggit.models import Tag
from django.db.models import Q

# Create your views here.

def home(request):
    posts = Post.objects.all().order_by('-published_date')[:5]  # Get latest 5 posts
    return render(request, 'blog/home.html', {'posts': posts})


# Custom Registration View
class RegisterView(CreateView):
    form_class = CustomUserCreationForm
    template_name = 'blog/register.html'
    success_url = reverse_lazy('blog:login')
    
    def form_valid(self, form):
        user = form.save()
        messages.success(self.request, f'Account created for {user.username}! You can now log in.')
        return super().form_valid(form)


# Custom Login View
class CustomLoginView(LoginView):
    template_name = 'blog/login.html'
    redirect_authenticated_user = True
    
    def get_success_url(self):
        return reverse_lazy('blog:home')
    
    def form_valid(self, form):
        messages.success(self.request, f'Welcome back, {form.get_user().username}!')
        return super().form_valid(form)


# Custom Logout View
class CustomLogoutView(LogoutView):
    template_name = 'blog/logout.html'
    
    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            messages.success(request, 'You have been logged out successfully!')
        return super().dispatch(request, *args, **kwargs)
    
    def get(self, request, *args, **kwargs):
        """Handle GET request for logout"""
        return self.post(request, *args, **kwargs)


# Profile View
@login_required
def profile(request):
    if request.method == 'POST':
        form = UserUpdateForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your profile has been updated successfully!')
            return redirect('blog:profile')
    else:
        form = UserUpdateForm(instance=request.user)
    
    return render(request, 'blog/profile.html', {'form': form})


# Blog Post CRUD Views

class PostListView(ListView):
    model = Post
    template_name = 'blog/post_list.html'
    context_object_name = 'posts'
    ordering = ['-published_date']
    paginate_by = 5

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'All Posts'
        return context


class PostDetailView(DetailView):
    model = Post
    template_name = 'blog/post_detail.html'
    context_object_name = 'post'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['comments'] = self.object.comments.all().order_by('created_at')
        context['comment_form'] = CommentForm()
        return context


class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    form_class = PostForm
    template_name = 'blog/post_form.html'
    
    def form_valid(self, form):
        form.instance.author = self.request.user
        messages.success(self.request, 'Your post has been created successfully!')
        return super().form_valid(form)
    
    def get_success_url(self):
        return reverse_lazy('blog:post-detail', kwargs={'pk': self.object.pk})


class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Post
    form_class = PostForm
    template_name = 'blog/post_form.html'
    
    def form_valid(self, form):
        form.instance.author = self.request.user
        messages.success(self.request, 'Your post has been updated successfully!')
        return super().form_valid(form)
    
    def test_func(self):
        post = self.get_object()
        return self.request.user == post.author
    
    def get_success_url(self):
        return reverse_lazy('blog:post-detail', kwargs={'pk': self.object.pk})


class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Post
    template_name = 'blog/post_confirm_delete.html'
    context_object_name = 'post'
    success_url = reverse_lazy('blog:post-list')
    
    def test_func(self):
        post = self.get_object()
        return self.request.user == post.author
    
    def delete(self, request, *args, **kwargs):
        messages.success(self.request, 'Your post has been deleted successfully!')
        return super().delete(request, *args, **kwargs)


# Comment Views

class CommentCreateView(LoginRequiredMixin, CreateView):
    model = Comment
    form_class = CommentForm
    template_name = 'blog/add_comment.html'
    
    def form_valid(self, form):
        post = get_object_or_404(Post, pk=self.kwargs['pk'])
        form.instance.post = post
        form.instance.author = self.request.user
        messages.success(self.request, 'Your comment has been added successfully!')
        return super().form_valid(form)
    
    def get_success_url(self):
        return reverse_lazy('blog:post-detail', kwargs={'pk': self.object.post.pk})
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['post'] = get_object_or_404(Post, pk=self.kwargs['pk'])
        return context


class CommentUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Comment
    form_class = CommentForm
    template_name = 'blog/edit_comment.html'
    
    def test_func(self):
        comment = self.get_object()
        return self.request.user == comment.author
    
    def form_valid(self, form):
        messages.success(self.request, 'Your comment has been updated successfully!')
        return super().form_valid(form)
    
    def get_success_url(self):
        return reverse_lazy('blog:post-detail', kwargs={'pk': self.object.post.pk})


class CommentDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Comment
    template_name = 'blog/delete_comment.html'
    context_object_name = 'comment'
    
    def test_func(self):
        comment = self.get_object()
        return self.request.user == comment.author
    
    def delete(self, request, *args, **kwargs):
        messages.success(self.request, 'Your comment has been deleted successfully!')
        return super().delete(request, *args, **kwargs)
    
    def get_success_url(self):
        return reverse_lazy('blog:post-detail', kwargs={'pk': self.object.post.pk})


class PostByTagListView(ListView):
    model = Post
    template_name = 'blog/post_list.html'
    context_object_name = 'posts'
    paginate_by = 5

    def get_queryset(self):
        self.tag = get_object_or_404(Tag, slug=self.kwargs['tag_slug'])
        return Post.objects.filter(tags=self.tag).order_by('-published_date')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = f'Posts tagged with "{self.tag.name}"'
        context['tag'] = self.tag
        return context


def search(request):
    query = request.GET.get('q')
    if query:
        posts = Post.objects.filter(
            Q(title__icontains=query) |
            Q(content__icontains=query) |
            Q(tags__name__icontains=query)
        ).distinct().order_by('-published_date')
    else:
        posts = Post.objects.none()

    context = {
        'posts': posts,
        'query': query,
        'title': f'Search results for "{query}"'
    }
    return render(request, 'blog/search_results.html', context)

django_blog/blog/templates/blog/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Django Blog</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'blog/style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand" href="{% url 'blog:home' %}">Django Blog</a>
            <div class="navbar-nav me-auto">
                <a class="nav-link" href="{% url 'blog:home' %}">Home</a>
                <a class="nav-link" href="{% url 'blog:post-list' %}">All Posts</a>
                {% if user.is_authenticated %}
                <a class="nav-link" href="{% url 'blog:post-create' %}">Create Post</a>
                {% endif %}
            </div>
            <form class="d-flex" action="{% url 'blog:search' %}" method="get">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="q">
                <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
            <div class="navbar-nav ms-auto">
                {% if user.is_authenticated %}
                <span class="navbar-text me-3">Welcome, {{ user.username }}!</span>
                <a class="nav-link" href="{% url 'blog:profile' %}">Profile</a>
                <a class="nav-link" href="{% url 'blog:logout' %}">Logout</a>
                {% else %}
                <a class="nav-link" href="{% url 'blog:login' %}">Login</a>
                <a class="nav-link" href="{% url 'blog:register' %}">Register</a>
                {% endif %}
            </div>
        </div>
    </nav>

    <main class="container mt-4">
        {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
            {{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
        </div>
        {% endfor %}
        {% endif %}

        {% block content %}
        {% endblock %}
    </main>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
</body>

</html>

django_blog/blog/templates/blog/home.html
{% extends 'blog/base.html' %}

{% block content %}
<div class="row">
    <div class="col-md-8">
        <h1>Welcome to Django Blog</h1>
        <p class="lead">A comprehensive blogging platform built with Django.</p>

        {% if posts %}
        <h2>Latest Posts</h2>
        {% for post in posts %}
        <article class="blog-post">
            <h3 class="post-title">
                <a href="{% url 'blog:post-detail' post.pk %}">{{ post.title }}</a>
            </h3>
            <p class="post-meta">
                By {{ post.author.username }} on {{ post.published_date|date:"F d, Y" }}
            </p>
            <p>{{ post.content|truncatewords:30 }}</p>
            <a href="{% url 'blog:post-detail' post.pk %}" class="btn btn-outline-primary btn-sm">Read More</a>
        </article>
        {% endfor %}
        {% else %}
        <div class="alert alert-info">
            <h4>No posts yet!</h4>
            <p>Be the first to create a blog post.</p>
            {% if user.is_authenticated %}
            <a href="{% url 'blog:post-create' %}" class="btn btn-primary">Create Your First Post</a>
            {% else %}
            <a href="{% url 'blog:register' %}" class="btn btn-primary">Register to Start Blogging</a>
            {% endif %}
        </div>
        {% endif %}
    </div>

    <div class="col-md-4">
        <div class="card">
            <div class="card-header">
                <h5>Quick Actions</h5>
            </div>
            <div class="card-body">
                {% if user.is_authenticated %}
                <a href="{% url 'blog:post-create' %}" class="btn btn-primary btn-sm d-block mb-2">Create New Post</a>
                <a href="{% url 'blog:profile' %}" class="btn btn-outline-primary btn-sm d-block">Manage Profile</a>
                {% else %}
                <a href="{% url 'blog:register' %}" class="btn btn-primary btn-sm d-block mb-2">Register</a>
                <a href="{% url 'blog:login' %}" class="btn btn-outline-primary btn-sm d-block">Login</a>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

django_blog/blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}

{% block content %}
<div class="row">
    <div class="col-md-8">
        <article class="blog-post">
            <h1 class="post-title">{{ post.title }}</h1>
            <div class="post-meta mb-4">
                <p class="text-muted">
                    By <strong>{{ post.author.username }}</strong> on
                    {{ post.published_date|date:"F d, Y g:i A" }}
                </p>

                {% if user == post.author %}
                <div class="mt-3">
                    <a href="{% url 'blog:post-update' post.pk %}" class="btn btn-warning btn-sm">
                        <i class="bi bi-pencil"></i> Edit Post
                    </a>
                    <a href="{% url 'blog:post-delete' post.pk %}" class="btn btn-danger btn-sm">
                        <i class="bi bi-trash"></i> Delete Post
                    </a>
                </div>
                {% endif %}
            </div>

            <div class="post-content">
                <div class="lead mb-4">
                    {{ post.content|linebreaks }}
                </div>
            </div>

            <div class="post-tags mt-4">
                <strong>Tags:</strong>
                {% for tag in post.tags.all %}
                <a href="{% url 'blog:tagged' tag.slug %}" class="badge bg-primary text-decoration-none">{{ tag.name
                    }}</a>
                {% empty %}
                <span class="text-muted">No tags yet.</span>
                {% endfor %}
            </div>

            <hr>

            <!-- Comments Section -->
            <div class="comments-section mt-4">
                <h4 class="mb-3">Comments ({{ comments.count }})</h4>

                {% if user.is_authenticated %}
                <div class="add-comment-section mb-4">
                    <h5>Leave a Comment</h5>
                    <a href="{% url 'blog:add_comment' post.pk %}" class="btn btn-primary">
                        <i class="bi bi-chat-dots"></i> Add Comment
                    </a>
                </div>
                {% else %}
                <div class="mb-4">
                    <p class="text-muted">
                        <a href="{% url 'blog:login' %}">Log in</a> to leave a comment.
                    </p>
                </div>
                {% endif %}

                <!-- Display Comments -->
                {% if comments %}
                <div class="comments-list">
                    {% for comment in comments %}
                    <div class="card mb-3">
                        <div class="card-body">
                            <div class="d-flex justify-content-between align-items-start">
                                <div class="comment-meta">
                                    <h6 class="card-subtitle mb-2 text-primary">
                                        {{ comment.author.username }}
                                    </h6>
                                    <small class="text-muted">
                                        {{ comment.created_at|date:"F d, Y g:i A" }}
                                        {% if comment.updated_at != comment.created_at %}
                                        (edited {{ comment.updated_at|date:"F d, Y g:i A" }})
                                        {% endif %}
                                    </small>
                                </div>

                                {% if user == comment.author %}
                                <div class="comment-actions">
                                    <a href="{% url 'blog:edit_comment' comment.pk %}"
                                        class="btn btn-outline-warning btn-sm me-1">
                                        <i class="bi bi-pencil"></i> Edit
                                    </a>
                                    <a href="{% url 'blog:delete_comment' comment.pk %}"
                                        class="btn btn-outline-danger btn-sm">
                                        <i class="bi bi-trash"></i> Delete
                                    </a>
                                </div>
                                {% endif %}
                            </div>

                            <div class="comment-content mt-3">
                                {{ comment.content|linebreaks }}
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
                {% else %}
                <div class="no-comments">
                    <p class="text-muted">No comments yet. Be the first to comment!</p>
                </div>
                {% endif %}
            </div>

            <hr>

            <div class="post-navigation">
                <a href="{% url 'blog:post-list' %}" class="btn btn-outline-primary">
                    <i class="bi bi-arrow-left"></i> Back to All Posts
                </a>
                <a href="{% url 'blog:home' %}" class="btn btn-outline-secondary">
                    <i class="bi bi-house"></i> Home
                </a>
            </div>
        </article>
    </div>

    <div class="col-md-4">
        <div class="card">
            <div class="card-header">
                <h5>Post Actions</h5>
            </div>
            <div class="card-body">
                {% if user == post.author %}
                <a href="{% url 'blog:post-update' post.pk %}" class="btn btn-warning btn-sm d-block mb-2">
                    Edit This Post
                </a>
                <a href="{% url 'blog:post-delete' post.pk %}" class="btn btn-danger btn-sm d-block mb-2">
                    Delete This Post
                </a>
                <hr>
                {% endif %}

                <a href="{% url 'blog:post-list' %}" class="btn btn-outline-primary btn-sm d-block mb-2">
                    View All Posts
                </a>

                {% if user.is_authenticated %}
                <a href="{% url 'blog:post-create' %}" class="btn btn-success btn-sm d-block mb-2">
                    Create New Post
                </a>
                {% endif %}

                <a href="{% url 'blog:home' %}" class="btn btn-outline-secondary btn-sm d-block">
                    Home
                </a>
            </div>
        </div>

        <div class="card mt-3">
            <div class="card-header">
                <h5>About Author</h5>
            </div>
            <div class="card-body">
                <p><strong>Username:</strong> {{ post.author.username }}</p>
                {% if post.author.first_name or post.author.last_name %}
                <p><strong>Name:</strong> {{ post.author.first_name }} {{ post.author.last_name }}</p>
                {% endif %}
                <p><strong>Posts by {{ post.author.username }}:</strong> {{ post.author.blog_posts.count }}</p>
                <p><strong>Member since:</strong> {{ post.author.date_joined|date:"F Y" }}</p>
            </div>
        </div>
    </div>
</div>
{% endblock %}

django_blog/blog/templates/blog/post_list.html
{% extends 'blog/base.html' %}

{% block content %}
<div class="row">
    <div class="col-md-8">
        <div class="d-flex justify-content-between align-items-center mb-4">
            <h2>{{ title }}</h2>
            {% if user.is_authenticated %}
            <a href="{% url 'blog:post-create' %}" class="btn btn-primary">Create New Post</a>
            {% endif %}
        </div>

        {% if posts %}
        {% for post in posts %}
        <article class="blog-post">
            <h3 class="post-title">
                <a href="{% url 'blog:post-detail' post.pk %}">{{ post.title }}</a>
            </h3>
            <p class="post-meta">
                By <strong>{{ post.author.username }}</strong> on {{ post.published_date|date:"F d, Y g:i A" }}
                {% if user == post.author %}
                <span class="ms-3">
                    <a href="{% url 'blog:post-update' post.pk %}" class="btn btn-outline-warning btn-sm">Edit</a>
                    <a href="{% url 'blog:post-delete' post.pk %}" class="btn btn-outline-danger btn-sm">Delete</a>
                </span>
                {% endif %}
            </p>
            <p>{{ post.content|truncatewords:50 }}</p>
            <div class="post-tags">
                <strong>Tags:</strong>
                {% for tag in post.tags.all %}
                <a href="{% url 'blog:tagged' tag.slug %}" class="badge bg-primary text-decoration-none">{{ tag.name
                    }}</a>
                {% empty %}
                <span class="text-muted">No tags.</span>
                {% endfor %}
            </div>
            <a href="{% url 'blog:post-detail' post.pk %}" class="btn btn-outline-primary btn-sm mt-2">Read More</a>
        </article>
        {% endfor %}

        <!-- Pagination -->
        {% if is_paginated %}
        <nav aria-label="Blog posts pagination">
            <ul class="pagination justify-content-center">
                {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page=1">First</a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a>
                </li>
                {% endif %}

                <li class="page-item active">
                    <span class="page-link">
                        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
                    </span>
                </li>

                {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
                </li>
                {% endif %}
            </ul>
        </nav>
        {% endif %}
        {% else %}
        <div class="alert alert-info text-center">
            <h4>No posts found</h4>
            <p>There are no blog posts yet.</p>
            {% if user.is_authenticated %}
            <a href="{% url 'blog:post-create' %}" class="btn btn-primary">Create the First Post</a>
            {% else %}
            <p><a href="{% url 'blog:register' %}">Register</a> to start creating posts.</p>
            {% endif %}
        </div>
        {% endif %}
    </div>

    <div class="col-md-4">
        <div class="card">
            <div class="card-header">
                <h5>Blog Stats</h5>
            </div>
            <div class="card-body">
                <p><strong>Total Posts:</strong> {{ posts|length|default:0 }}</p>
                {% if user.is_authenticated %}
                <p><strong>Your Posts:</strong> {{ user.blog_posts.count }}</p>
                {% endif %}
            </div>
        </div>

        <div class="card mt-3">
            <div class="card-header">
                <h5>Quick Actions</h5>
            </div>
            <div class="card-body">
                {% if user.is_authenticated %}
                <a href="{% url 'blog:post-create' %}" class="btn btn-success btn-sm d-block mb-2">Create New Post</a>
                <a href="{% url 'blog:home' %}" class="btn btn-outline-primary btn-sm d-block mb-2">Home</a>
                <a href="{% url 'blog:profile' %}" class="btn btn-outline-secondary btn-sm d-block">Profile</a>
                {% else %}
                <a href="{% url 'blog:register' %}" class="btn btn-primary btn-sm d-block mb-2">Register</a>
                <a href="{% url 'blog:login' %}" class="btn btn-outline-primary btn-sm d-block">Login</a>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

django_blog/blog/templates/blog/search_results.html
{% extends 'blog/base.html' %}

{% block content %}
<div class="row">
    <div class="col-md-8">
        <h2 class="mb-4">Search Results for "{{ query }}"</h2>

        {% if posts %}
        {% for post in posts %}
        <article class="blog-post">
            <h3 class="post-title"><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h3>
            <p class="post-meta">By <strong>{{ post.author.username }}</strong> on {{ post.published_date|date:"F d, Y"
                }}</p>
            <p>{{ post.content|truncatewords:50 }}</p>
            <div class="post-tags">
                <strong>Tags:</strong>
                {% for tag in post.tags.all %}
                <a href="{% url 'blog:tagged' tag.slug %}" class="badge bg-primary text-decoration-none">{{ tag.name
                    }}</a>
                {% empty %}
                <span class="text-muted">No tags.</span>
                {% endfor %}
            </div>
            <a href="{{ post.get_absolute_url }}" class="btn btn-outline-primary btn-sm mt-2">Read More</a>
        </article>
        {% endfor %}
        {% else %}
        <div class="alert alert-warning">
            <p>No posts found matching your search criteria.</p>
        </div>
        {% endif %}
    </div>
    <div class="col-md-4">
        <div class="card">
            <div class="card-header">
                <h5>Search Again</h5>
            </div>
            <div class="card-body">
                <form method="get" action="{% url 'blog:search' %}">
                    <div class="input-group">
                        <input type="text" name="q" class="form-control" placeholder="Search for..."
                            value="{{ query|default:'' }}">
                        <button class="btn btn-outline-secondary" type="submit">Go!</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}